dist: trusty
sudo: false
os:
  - linux
install:
  - mkdir -p hardware/keyboardio
  - ln -s `pwd` hardware/keyboardio/avr
script:
  - make travis-test-all BOARD_HARDWARE_PATH=$(pwd)/hardware
# Blacklist
branches:
  except:
    - gh-pages
env:
  global:
    - GH_REPO_NAME: Arduino-Boards
    - DOXYFILE: $TRAVIS_BUILD_DIR/etc/doxygen/doxygen.conf
    - GH_REPO_REF: github.com/keyboardio/Arduino-Boards.git

notifications:
  irc:
    channels:
      - "chat.freenode.net#keyboardio"
    use_notice: true
    skip_join: true
    template:
      - "%{repository_name}/%{branch} %{commit} by %{author}: %{commit_subject} %{build_url} %{message}" 
  email:
    on_success: change
    on_failure: change
cache:
  ccache: true
# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - sh ./build-tools/doxygen-deploy.sh

